language: python
env:
  global:
  - TARGET_REPO_SLUG=fonflatter/test-content
  - TARGET_REPO_BRANCH=master
install:
- git clone --depth 1 https://github.com/fonflatter/util/ ~/util/
- ~/util/prepare.sh "$encrypted_36f03a76214f_key" "$encrypted_36f03a76214f_iv"
script: ~/util/merge.sh
