language: python
env:
- OUTPUT_DIR=~/build/fonflatter/test-content
before_install:
- openssl aes-256-cbc -K $encrypted_36f03a76214f_key -iv $encrypted_36f03a76214f_iv
  -in .ssh/id_rsa.enc -out ~/.ssh/id_rsa -d
- chmod og-rw ~/.ssh/id_rsa
- git config --global user.name "fredobot"
- git config --global user.email "fredobot@winniehell.de"
install: "git clone -o github -b master git@github.com:fonflatter/test-content.git $OUTPUT_DIR"
before_script:
- curl https://raw.githubusercontent.com/fonflatter/util/master/merge.sh > ~/merge.sh
- chmod u+x ~/merge.sh
script: ~/merge.sh
